# PZPU - Pseudo-ZPU emulator
# (C) MatrixS_Master, 2016
# GPL v2
#

.PHONY: all
all:
	make -f Makefile.pc

.PHONY: avr
avr:
	make -f Makefile.avr
	
.PHONY: clean
clean:
	make -f Makefile.pc clean
	make -f Makefile.avr clean
